/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.reservation;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Java
 */
public class flight extends javax.swing.JInternalFrame {

    /**
     * Creates new form flight
     */
    public flight() throws SQLException {
        initComponents();
    autoId();
    }
    Connection con;
    PreparedStatement pt;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        txtfarr = new javax.swing.JTextField();
        txtfdep = new javax.swing.JTextField();
        txtfdest = new javax.swing.JComboBox<>();
        txtfsource = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtflightid = new javax.swing.JLabel();
        txtflightnamelable = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fdate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txtfprice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();

        setTitle("Add Flight");
        setToolTipText("");

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Arrival");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 199, 120, -1));
        kGradientPanel1.add(txtfarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 87, -1));
        kGradientPanel1.add(txtfdep, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 87, -1));

        txtfdest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Mumbai", "Banglore", "Kolkata", "Hydrabad", "Chennai", "New york", "London", "Dubai" }));
        kGradientPanel1.add(txtfdest, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        txtfsource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Mumbai", "Banglore", "Kolkata", "Hydrabad", "Chennai", "New york", "London", "Dubai" }));
        kGradientPanel1.add(txtfsource, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Source");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 85, 120, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Destination");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 125, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Departure");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 162, 120, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("FLIGHTS");
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 18, 120, 45));

        txtflightid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtflightid.setForeground(new java.awt.Color(255, 255, 255));
        txtflightid.setText("001");
        kGradientPanel1.add(txtflightid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 45, -1));

        txtflightnamelable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtflightnamelable.setForeground(new java.awt.Color(255, 255, 255));
        txtflightnamelable.setText("Flight Name");
        kGradientPanel1.add(txtflightnamelable, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        txtfname.setOpaque(true);
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 110, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 91, -1, -1));

        fdate.setOpaque(false);
        kGradientPanel1.add(fdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 85, 114, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Price");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        txtfprice.setOpaque(true);
        kGradientPanel1.add(txtfprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 114, -1));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("AIR");
        kGradientPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 60, 30));

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ticket Booking");
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 120, 30));

        kButton1.setText("Cancel");
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 120, -1));

        kButton2.setText("ADD");
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
     public void autoId() throws SQLException{
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/airline","root","");
            
            Statement s =   con.createStatement();
            ResultSet rs;
            rs = s.executeQuery("select MAX(flightid) from flight");
            rs.next();
            rs.getString("MAX(flightid)");
            
            if(rs.getString("MAX(flightid)")==null){
                txtflightid.setText("001");
            }
            else{
                long id = Long.parseLong(rs.getString("MAX(flightid)"));
                    id++;
                    txtflightid.setText(String.format("%03d",id));
                
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Add_customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
          String flightid = txtflightid.getText();
         String name = txtfname.getText();
        String source = txtfsource.getSelectedItem().toString();
        String departure = txtfdep.getText();
        String destination = txtfdest.getSelectedItem().toString();
        String arrival = txtfarr.getText();
        String price = txtfprice.getText();
       
        
        DateFormat dt = new SimpleDateFormat("yyyy-mm-dd");
        String date = dt.format(fdate.getDate());
        
        
       
        
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/airline","root","");
            pt =con.prepareStatement("insert into flight (flightid,flightname,source,destination,departure,arrival,date,price)value(?,?,?,?,?,?,?,?)");
            
            pt.setString(1,flightid );
            pt.setString(2,name );
            pt.setString(3,source);
            pt.setString(4,destination);
            pt.setString(5,departure);
            pt.setString(6,arrival);
            pt.setString(7,date);
            pt.setString(8,price);
            
           
            
            pt.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "record updated success");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Add_customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Add_customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        this.hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton1ActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fdate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txtfarr;
    private javax.swing.JTextField txtfdep;
    private javax.swing.JComboBox<String> txtfdest;
    private javax.swing.JLabel txtflightid;
    private javax.swing.JLabel txtflightnamelable;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtfprice;
    private javax.swing.JComboBox<String> txtfsource;
    // End of variables declaration//GEN-END:variables
}
